branch-defaults:
  default:
    environment: null
    group_suffix: null
deploy:
  artifact: target/site-0.0.1.jar
global:
  application_name: real-estate
  branch: null
  default_ec2_keyname: note
  default_platform: Java 8
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
